[package]
name = "cycle-rpc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
cycle-proto = { path = "../../proto" }
tokio = { version = "1.40", features = ["rt-multi-thread"] }
tonic = "0.12"
